server:
  port: 8091
spring:
  datasource:
    url:jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username=sa
    password=
  liquibase:
    enabled: false
    enable: false
#    change-log: classpath:changelogs/changeLog.yaml