spring:
  datasource:
    url:jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username=sa
    password=
  liquibase:
    change-log: classpath:changelogs/changeLog.yaml
downstream:
  service:
    vehicle-url: http://localhost:8091